name: Build and push docker image to dockerhub
# testing
on:
  push:
    branches:
      - 'main'
      
env:
  IMAGE_NAME: note-app
  IMAGE_TAG: latest

jobs:
  docker:
    runs-on: [self-hosted]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker_cicd_github_action/.
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_NAME }}