name: Deploy to EKS
on:
 #testing125
  push:
    branches: [ master ]
  workflow_dispatch:
env:
  EKS_CLUSTER_NAME: cicd-cluster
  AWS_REGION: us-east-1
  DOCKER_REPOSITORY: noted-app
jobs:
  
  build:
    
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build, tag, and push image to Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}        
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG .
        docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG
    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
    - name: Update Image tag
      env:       
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        sed -i.bak "s|latest|$IMAGE_TAG|g" helm-chart/docker-cicd/values.yaml
    
    - name: update docker Username and Image name
      env: 
        USER_NAME: ${{ secrets.DOCKERHUB_USERNAME }}
        IMAGE_NAME: ${{ env.DOCKER_REPOSITORY }}
      run: |
        sed -i.bak "s|username|$USER_NAME|g" helm-chart/docker-cicd/values.yaml && \
        sed -i.bak "s|imagename|$IMAGE_NAME|g" helm-chart/docker-cicd/values.yaml
    - name: Deploy helm chart
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm upgrade --install docker-cicd helm-chart/docker-cicd/